In [1]:
import pandas as pd
import re

In [2]:
acreage = pd.read_csv('../data/national-park-service/nps_acreage_2023.csv', encoding='latin-1')

In [3]:
np_acres = acreage.loc[(acreage['Area Name'].str.endswith('NP'))
           |(acreage['Area Name'].str.endswith('NP & PRES'))
           |(acreage['Area Name'].str.endswith('BLACK CANYON OF GUNNISON'))
           |(acreage['Area Name'].str.endswith('NP OF AMERICAN SAMOA'))]

In [4]:
np_acres = np_acres.drop(columns=['Region'
                               ,'Unnamed: 11'
                               ,'Unnamed: 12'
                               ,'Unnamed: 13'])

In [5]:
np_acres['park_name'] = np_acres['Area Name'].str.title()

In [6]:
for index, fields in np_acres.iterrows():
    if fields.park_name.endswith('Samoa'):
        np_acres.loc[index, 'park_name'] = 'American Samoa'
    elif fields.park_name.startswith('T Roosevelt'):
        np_acres.loc[index, 'park_name'] = 'Theodore Roosevelt'
    elif fields.park_name.startswith('Black Canyon'):
        np_acres.loc[index, 'park_name'] = 'Black Canyon of the Gunnison'
    elif fields.park_name.endswith(' Np'):
        np_acres.loc[index, 'park_name'] = fields.park_name[:-3]
    elif fields.park_name.endswith(' Np & Pres'):
        np_acres.loc[index, 'park_name'] = fields.park_name[:-10]
    
np_acres = np_acres.sort_values(by='park_name').reset_index(drop=True)

In [10]:
np_acres = np_acres.drop(columns='Area Name')

In [12]:
np_acres

,State,NPS Fee Acres,NPS Less Than Fee Acres,Other Federal Fee Acres,Subtotal Federal Acres,Other Public Acres,Private Acres,Subtotal Non-Federal Acres,Gross Area Acres,park_name
0,ME,"37,481.07","10,707.90",21.77,"48,210.74",48.22,812.44,860.66,"49,071.40",Acadia
1,SAMOA,0.00,0.00,0.00,0.00,"8,256.67",0.00,"8,256.67","8,256.67",American Samoa
2,UT,"76,545.95",0.00,0.00,"76,545.95",133.03,0.00,133.03,"76,678.98",Arches
3,SD,"111,485.13","122,324.00",0.00,"233,809.13",39.24,"8,907.57","8,946.81","242,755.94",Badlands
4,TX,"775,273.38",0.00,0.00,"775,273.38","2,606.87","23,282.96","25,889.83","801,163.21",Big Bend
...,...,...,...,...,...,...,...,...,...,...
58,SD,"33,970.84",0.00,0.00,"33,970.84",0.00,0.00,0.00,"33,970.84",Wind Cave
59,AK,"7,956,729.18",0.83,0.00,"7,956,730.01","17,577.06","348,839.41","366,416.47","8,323,146.48",Wrangell-St Elias
60,ID-MT-WY,"2,219,789.13",0.00,0.00,"2,219,789.13",0.00,1.58,1.58,"2,219,790.71",Yellowstone
61,CA,"759,690.11",10.83,319.11,"760,020.05","1,502.70",224.75,"1,727.45","761,747.50",Yosemite
62,UT,"143,793.41",0.00,0.00,"143,793.41",5.13,"3,444.12","3,449.25","147,242.66",Zion

In [13]:
np_acres.to_csv('../data/final/acreage.csv', index=False)