In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from datetime import datetime as dt

In [2]:
np = pd.read_csv('../data/np_data.csv')

In [3]:
np.date_established = pd.to_datetime(np.date_established)

In [4]:
np.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63 entries, 0 to 62
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   park_name                63 non-null     object
 1   date_established         63 non-null     datetime64[ns]
 2   description              63 non-null     object
 3   area_acres               63 non-null     float64
 4   area_km2                 63 non-null     object
 5   state                    63 non-null     object
 6   recreational_visits      59 non-null     float64
 7   non_recreational_visits  59 non-null     float64
 8   recreational_hours       59 non-null     float64
 9   non_recreational_hours   59 non-null     float64
 10  tent_overnights          59 non-null     float64
 11  rv_overnights            59 non-null     float64
 12  backcountry_overnights   59 non-null     float64
dtypes: datetime64[ns](1), float64(8), object(4)
memory usage: 6.5+ KB

In [5]:
np.head(1)

,park_name,date_established,description,area_acres,area_km2,state,recreational_visits,non_recreational_visits,recreational_hours,non_recreational_hours,tent_overnights,rv_overnights,backcountry_overnights
0,Acadia,1919-02-26,Covering most of Mount Desert Island and other...,49071.4,198.6,Maine,3879890.0,47100.0,25804425.0,47100.0,120615.0,49074.0,1570.0

In [6]:
np.tail(1)

,park_name,date_established,description,area_acres,area_km2,state,recreational_visits,non_recreational_visits,recreational_hours,non_recreational_hours,tent_overnights,rv_overnights,backcountry_overnights
62,Zion,1919-11-19,Located at the junction of the Colorado Platea...,147242.66,595.9,Utah,4623238.0,21900.0,29471316.0,5475.0,100411.0,85948.0,8497.0

In [7]:
np.describe()

,date_established,area_acres,recreational_visits,non_recreational_visits,recreational_hours,non_recreational_hours,tent_overnights,rv_overnights,backcountry_overnights
count,63,6.300000e+01,5.900000e+01,5.900000e+01,5.900000e+01,5.900000e+01,59.000000,59.000000,59.000000
mean,1957-08-17 00:00:00,8.326318e+05,1.523528e+06,3.833077e+05,1.214331e+07,2.772437e+05,37062.813559,26067.779661,22770.322034
min,1872-03-01 00:00:00,1.928300e+02,1.104500e+04,0.000000e+00,1.012560e+05,0.000000e+00,0.000000,0.000000,0.000000
25%,1924-08-29 12:00:00,5.859319e+04,3.722970e+05,4.700000e+01,1.649430e+06,6.000000e+01,0.000000,0.000000,579.000000
50%,1968-10-02 00:00:00,2.182224e+05,7.036590e+05,7.025000e+03,4.418935e+06,1.929600e+04,8136.000000,8839.000000,4378.000000
75%,1980-12-02 00:00:00,7.156988e+05,2.442052e+06,5.279200e+04,1.206282e+07,9.199300e+04,47098.500000,29248.000000,26800.500000
max,2020-12-27 00:00:00,8.323146e+06,1.329765e+07,1.083200e+07,9.808363e+07,5.416000e+06,275278.000000,196092.000000,299725.000000
std,NaN,1.632137e+06,2.069543e+06,1.525884e+06,1.999669e+07,9.115640e+05,59641.443355,41637.064920,47438.648627

In [8]:
np.corr(numeric_only=True)

,area_acres,recreational_visits,non_recreational_visits,recreational_hours,non_recreational_hours,tent_overnights,rv_overnights,backcountry_overnights
area_acres,1.000000,-0.095126,-0.013809,0.036804,-0.007696,-0.043391,-0.015893,0.054913
recreational_visits,-0.095126,1.000000,0.727589,0.851583,0.712149,0.674378,0.688276,0.425509
non_recreational_visits,-0.013809,0.727589,1.000000,0.564014,0.777835,0.323363,0.368350,0.188998
recreational_hours,0.036804,0.851583,0.564014,1.000000,0.653186,0.694731,0.697798,0.591675
non_recreational_hours,-0.007696,0.712149,0.777835,0.653186,1.000000,0.581999,0.624461,0.299267
tent_overnights,-0.043391,0.674378,0.323363,0.694731,0.581999,1.000000,0.951337,0.556631
rv_overnights,-0.015893,0.688276,0.368350,0.697798,0.624461,0.951337,1.000000,0.502357
backcountry_overnights,0.054913,0.425509,0.188998,0.591675,0.299267,0.556631,0.502357,1.000000

In [9]:
biodiversity = pd.read_csv('../data/biodiversity.csv')

In [10]:
biodiversity

,park_name,category,common_names
0,Acadia,Mammal,Moose
1,Acadia,Mammal,"Northern White-tailed Deer, Virginia Deer, Whi..."
2,Acadia,Mammal,"Coyote, Eastern Coyote"
3,Acadia,Mammal,"Black Fox, Cross Fox, Eastern Red Fox, Fox, Re..."
4,Acadia,Mammal,"Bay Lynx, Bobcat, Red Lynx, Wild Cat"
...,...,...,...
94906,Zion,Vascular Plant,cut-leaf nightshade
94907,Zion,Vascular Plant,canyon grape
94908,Zion,Vascular Plant,wine grape
94909,Zion,Vascular Plant,creosote bush
94910,Zion,Vascular Plant,puncture vine

In [11]:
category_counts = biodiversity.groupby(['park_name', 'category']).count()
category_counts

                          common_names
park_name category
Acadia    Amphibian                 11
          Bird                     214
          Fish                      33
          Mammal                    38
          Reptile                    7
...                                ...
Zion      Bird                     210
          Fish                       9
          Mammal                    68
          Reptile                   29
          Vascular Plant           996

[409 rows x 1 columns]

In [12]:
park_counts = biodiversity.park_name.value_counts().to_frame().sort_values(by='park_name').reset_index()
park_counts.head()

  park_name  count
0    Acadia   1169
1    Arches    754
2  Badlands    756
3  Big Bend   1991
4  Biscayne   1329

In [13]:
park_counts = park_counts.rename(columns={'count':'num_species'})
park_counts.head()

  park_name  num_species
0    Acadia         1169
1    Arches          754
2  Badlands          756
3  Big Bend         1991
4  Biscayne         1329

In [14]:
np_stats = np.merge(park_counts
                   ,how='inner'
                   ,left_on='park_name'
                   ,right_on='park_name')
np_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   park_name                56 non-null     object
 1   date_established         56 non-null     datetime64[ns]
 2   description              56 non-null     object
 3   area_acres               56 non-null     float64
 4   area_km2                 56 non-null     object
 5   state                    56 non-null     object
 6   recreational_visits      56 non-null     float64
 7   non_recreational_visits  56 non-null     float64
 8   recreational_hours       56 non-null     float64
 9   non_recreational_hours   56 non-null     float64
 10  tent_overnights          56 non-null     float64
 11  rv_overnights            56 non-null     float64
 12  backcountry_overnights   56 non-null     float64
 13  num_species              56 non-null     int64
dtypes: datetime64[ns](1), float64(8), int64(1), object(4)
memory usage: 6.3+ KB

In [15]:
np_stats.head()

,park_name,date_established,description,area_acres,area_km2,state,recreational_visits,non_recreational_visits,recreational_hours,non_recreational_hours,tent_overnights,rv_overnights,backcountry_overnights,num_species
0,Acadia,1919-02-26,Covering most of Mount Desert Island and other...,49071.40,198.6,Maine,3879890.0,47100.0,25804425.0,47100.0,120615.0,49074.0,1570.0,1169
1,Arches,1971-11-12,"This site features more than 2,000 natural san...",76678.98,310.3,Utah,1482045.0,0.0,5462987.0,0.0,14885.0,19602.0,175.0,754
2,Badlands,1978-11-10,"The Badlands are a collection of buttes, pinna...",242755.94,982.4,South Dakota,1046400.0,55984.0,4418935.0,27992.0,3262.0,910.0,1417.0,756
3,Big Bend,1944-06-12,Named for the prominent bend in the Rio Grande...,801163.21,3242.2,Texas,509129.0,2700.0,9585981.0,8100.0,23647.0,27175.0,58919.0,1991
4,Biscayne,1980-06-28,"The central part of Biscayne Bay, this mostly ...",172971.11,700.0,Florida,571242.0,0.0,1809966.0,0.0,1997.0,0.0,0.0,1329

In [16]:
def acresToSqMiles(acres):
    sq_miles = round(acres / 640.0, 2)
    return sq_miles

In [17]:
np_stats['area_sq_miles'] = np_stats.area_acres.apply(acresToSqMiles)

In [18]:
np_stats

,park_name,date_established,description,area_acres,area_km2,state,recreational_visits,non_recreational_visits,recreational_hours,non_recreational_hours,tent_overnights,rv_overnights,backcountry_overnights,num_species,area_sq_miles
0,Acadia,1919-02-26,Covering most of Mount Desert Island and other...,49071.40,198.6,Maine,3879890.0,47100.0,25804425.0,47100.0,120615.0,49074.0,1570.0,1169,76.67
1,Arches,1971-11-12,"This site features more than 2,000 natural san...",76678.98,310.3,Utah,1482045.0,0.0,5462987.0,0.0,14885.0,19602.0,175.0,754,119.81
2,Badlands,1978-11-10,"The Badlands are a collection of buttes, pinna...",242755.94,982.4,South Dakota,1046400.0,55984.0,4418935.0,27992.0,3262.0,910.0,1417.0,756,379.31
3,Big Bend,1944-06-12,Named for the prominent bend in the Rio Grande...,801163.21,3242.2,Texas,509129.0,2700.0,9585981.0,8100.0,23647.0,27175.0,58919.0,1991,1251.82
4,Biscayne,1980-06-28,"The central part of Biscayne Bay, this mostly ...",172971.11,700.0,Florida,571242.0,0.0,1809966.0,0.0,1997.0,0.0,0.0,1329,270.27
5,Black Canyon of the Gunnison,1999-10-21,The park protects a quarter of the Gunnison Ri...,30779.83,124.6,Colorado,357069.0,0.0,1918066.0,0.0,17248.0,14690.0,828.0,691,48.09
6,Bryce Canyon,1928-02-25,Bryce Canyon is a geological amphitheater on s...,35835.08,145.0,Utah,2461269.0,408397.0,13210794.0,122520.0,44897.0,44563.0,2667.0,790,55.99
7,Canyonlands,1964-09-12,This landscape was eroded into a maze of canyo...,337597.83,1366.2,Utah,800322.0,0.0,5096820.0,0.0,8136.0,8790.0,68953.0,869,527.50
8,Capitol Reef,1971-12-18,The park's Waterpocket Fold is a 100-mile (160...,241904.50,979.0,Utah,1268861.0,87886.0,1928949.0,87886.0,16534.0,31608.0,3115.0,1166,377.98
9,Carlsbad Caverns,1930-05-14,"Carlsbad Caverns has 117 caves, the longest of...",46766.45,189.3,New Mexico,394121.0,0.0,1499159.0,0.0,0.0,0.0,0.0,1429,73.07
10,Channel Islands,1980-03-05,Five of the eight Channel Islands are protecte...,249561.00,1009.9,California,328746.0,12197.0,4254417.0,292735.0,0.0,0.0,23881.0,1847,389.94
11,Congaree,2003-11-10,"On the Congaree River, this park is the larges...",26692.60,108.0,South Carolina,250114.0,0.0,999482.0,0.0,7912.0,0.0,614.0,1205,41.71
12,Crater Lake,1902-05-22,Crater Lake lies in the caldera of an ancient ...,183224.05,741.5,Oregon,559976.0,49600.0,3387684.0,24800.0,0.0,0.0,1530.0,1178,286.29
13,Cuyahoga Valley,2000-10-11,This park along the Cuyahoga River has waterfa...,32571.89,131.8,Ohio,2860059.0,0.0,8517581.0,0.0,0.0,0.0,0.0,1589,50.89
14,Death Valley,1994-10-31,"Death Valley is the hottest, lowest, and dries...",3408395.63,13793.3,California,1099632.0,44158.0,8182261.0,66236.0,71963.0,79442.0,6302.0,1439,5325.62
15,Denali,1917-02-26,"Centered on Denali, the tallest and most promi...",4740911.16,19185.8,Alaska,498722.0,847073.0,5985104.0,211768.0,0.0,0.0,29720.0,1790,7407.67
16,Dry Tortugas,1992-10-26,"The islands of the Dry Tortugas, at the wester...",64701.22,261.8,Florida,84285.0,1608.0,628830.0,19296.0,6320.0,0.0,0.0,757,101.10
17,Everglades,1934-05-30,The Everglades are the largest tropical wilder...,1508938.57,6106.5,Florida,810189.0,6000.0,4971781.0,27000.0,0.0,0.0,10411.0,1747,2357.72
18,Gates of the Arctic,1980-12-02,The country's northernmost park protects an ex...,7523897.45,30448.1,Alaska,11045.0,0.0,101256.0,0.0,0.0,0.0,4000.0,723,11756.09
19,Glacier,1910-05-11,The U.S. half of Waterton-Glacier Internationa...,1013126.39,4100.0,Montana,2933616.0,2644.0,32739858.0,22876.0,132219.0,132336.0,32074.0,1507,1583.01
20,Glacier Bay,1980-12-02,"Glacier Bay contains tidewater glaciers, mount...",3223383.43,13044.6,Alaska,703659.0,458.0,8869184.0,96100.0,669.0,0.0,3648.0,917,5036.54
21,Grand Canyon,1919-02-26,"The Grand Canyon, carved by the mighty Colorad...",1201647.03,4862.9,Arizona,4733705.0,12533.0,74052927.0,12533.0,159019.0,84332.0,299725.0,2626,1877.57
22,Grand Teton,1929-02-26,Grand Teton is the tallest mountain in the sce...,310044.36,1254.7,Wyoming,3417106.0,1570845.0,21814250.0,1570845.0,68.0,0.0,41705.0,1855,484.44
23,Great Basin,1986-10-27,"Based around Nevada's second tallest mountain,...",77180.00,312.3,Nevada,143265.0,1200.0,1515358.0,600.0,25844.0,20262.0,453.0,966,120.59
24,Great Sand Dunes,2004-09-24,"The tallest sand dunes in North America, up to...",107345.73,434.4,Colorado,512219.0,470.0,2967583.0,470.0,33106.0,21992.0,10579.0,746,167.73
25,Great Smoky Mountains,1934-06-15,"The Great Smoky Mountains, part of the Appalac...",522426.88,2114.2,North Carolina,13297647.0,10832000.0,98083629.0,5416000.0,207070.0,158211.0,84532.0,21287,816.29
26,Guadalupe Mountains,1972-09-30,"This park contains Guadalupe Peak, the highest...",86367.10,349.5,Texas,227340.0,1440.0,645221.0,1440.0,16731.0,8839.0,2508.0,1380,134.95
27,Hot Springs,1921-03-04,Hot Springs was originally established by Cong...,5554.15,22.5,Arkansas,2502967.0,150504.0,6849394.0,171574.0,28.0,22062.0,0.0,594,8.68
28,Indiana Dunes,2019-02-15,"Previously designated a national lakeshore, pa...",15349.08,62.1,Indiana,2765892.0,3943.0,7657687.0,1968.0,24360.0,12540.0,0.0,1888,23.98
29,Isle Royale,1940-04-03,The largest island in Lake Superior is a place...,571790.30,2314.0,Michigan,28965.0,94.0,1524902.0,48484.0,6166.0,0.0,30072.0,1225,893.42
30,Joshua Tree,1994-10-31,Covering large areas of the Colorado and Mojav...,795155.85,3217.9,California,3270404.0,12171.0,19156045.0,12171.0,200056.0,101514.0,17396.0,846,1242.43
31,Katmai,1980-12-02,This park on the Alaska Peninsula protects the...,3674529.33,14870.3,Alaska,33763.0,7025.0,609721.0,101346.0,6172.0,0.0,5564.0,1326,5741.45
32,Kenai Fjords,1980-12-02,"Near Seward on the Kenai Peninsula, this park ...",669650.05,2710.0,Alaska,387525.0,0.0,1237607.0,0.0,688.0,0.0,57.0,1218,1046.33
33,Kobuk Valley,1980-12-02,Kobuk Valley protects 61 miles (98 km) of the ...,1750716.16,7084.9,Alaska,17616.0,7700.0,226149.0,233200.0,0.0,0.0,6675.0,554,2735.49
34,Lake Clark,1980-12-02,The region around Lake Clark features four act...,2619816.49,10602.0,Alaska,16728.0,3223.0,142378.0,37862.0,0.0,0.0,4555.0,1732,4093.46
35,Lassen Volcanic,1916-08-09,"Lassen Peak, the largest lava dome volcano in ...",106589.02,431.4,California,418978.0,0.0,4111590.0,0.0,43752.0,21273.0,1168.0,1054,166.55
36,Mammoth Cave,1941-07-01,With more than 400 miles (640 km) of passagewa...,72472.87,293.3,Kentucky,654450.0,110436.0,5182291.0,55217.0,49753.0,20081.0,4378.0,1980,113.24
37,Mesa Verde,1906-06-29,"This area constitutes over 4,000 archaeologica...",52485.17,212.4,Colorado,505194.0,11860.0,3524612.0,11860.0,22008.0,28868.0,0.0,1102,82.01
38,Mount Rainier,1899-03-02,"Mount Rainier, an active stratovolcano, is the...",236381.64,956.6,Washington,1674294.0,849082.0,21060484.0,849082.0,59749.0,29628.0,53949.0,1195,369.35
39,New River Gorge,2020-12-27,The New River Gorge is the deepest river gorge...,7021.00,28.4 km2,West Virginia,1707223.0,2400.0,4447173.0,4800.0,17214.0,10501.0,12609.0,2766,10.97
40,North Cascades,1968-10-02,The highly glaciated mountains of the North Ca...,504780.94,2042.8,Washington,40351.0,0.0,531844.0,0.0,0.0,0.0,19125.0,2969,788.72
41,Olympic,1938-06-29,This park on the Olympic Peninsula includes a ...,922649.41,3733.8,Washington,2947503.0,1045102.0,15497301.0,336937.0,121314.0,91536.0,158254.0,1376,1441.64
42,Petrified Forest,1962-12-09,This portion of the Chinle Formation has a lar...,221390.21,895.9,Arizona,520491.0,120.0,1350691.0,120.0,0.0,0.0,722.0,727,345.92
43,Pinnacles,2013-01-10,Named for the eroded leftovers of a portion of...,26685.73,108.0,California,341220.0,0.0,1925335.0,0.0,0.0,0.0,0.0,1180,41.70
44,Redwood,1968-10-02,This park and the co-managed state parks prote...,138999.37,562.5,California,409105.0,10824.0,1773959.0,2724.0,6554.0,0.0,13094.0,1461,217.19
45,Rocky Mountain,1915-01-26,Bisected north to south by the Continental Div...,265847.74,1075.8,Colorado,4115837.0,8750.0,26835519.0,26250.0,70761.0,28329.0,34314.0,1365,415.39
46,Saguaro,1994-10-14,Split into the separate Rincon Mountain and Tu...,92876.75,375.9,Arizona,1010906.0,4395013.0,1887764.0,1098754.0,0.0,0.0,3515.0,1572,145.12
47,Shenandoah,1935-12-26,Shenandoah's Blue Ridge Mountains are covered ...,200445.92,811.2,Virginia,1576008.0,10962.0,10914844.0,2742.0,122031.0,67815.0,67738.0,2569,313.20
48,Theodore Roosevelt,1978-11-10,This region that enticed and influenced Presid...,70446.89,285.1,North Dakota,746862.0,6578.0,2662270.0,2172.0,11703.0,21459.0,718.0,785,110.07
49,Virgin Islands,1956-08-02,This island park on Saint John preserves prist...,15052.33,60.9,U.S. Virgin Islands,343685.0,231252.0,2113667.0,70278.0,0.0,0.0,0.0,965,23.52
50,Voyageurs,1975-04-08,This park protecting four lakes near the Canad...,218222.35,883.1,Minnesota,220825.0,0.0,944753.0,0.0,0.0,0.0,56364.0,1144,340.97
51,White Sands,2019-12-20,"Located in the mountain-ringed Tularosa Basin,...",146344.31,592.2,New Mexico,729096.0,0.0,1425910.0,0.0,0.0,0.0,0.0,525,228.66
52,Wind Cave,1903-01-09,Wind Cave is distinctive for its calcite fin f...,33970.84,137.5,South Dakota,592459.0,236892.0,1826057.0,78174.0,5396.0,6500.0,544.0,991,53.08
53,Yellowstone,1872-03-01,"Situated on the Yellowstone Caldera, the park ...",2219790.71,8983.2,Wyoming,4501382.0,1306861.0,81677408.0,752457.0,25295.0,30413.0,38262.0,2076,3468.42
54,Yosemite,1890-10-01,"Yosemite features sheer granite cliffs, except...",761747.50,3082.7,California,3897070.0,160167.0,52057099.0,4245429.0,275278.0,196092.0,103997.0,1904,1190.23
55,Zion,1919-11-19,Located at the junction of the Colorado Platea...,147242.66,595.9,Utah,4623238.0,21900.0,29471316.0,5475.0,100411.0,85948.0,8497.0,1319,230.07

In [19]:
np_stats = np_stats.drop(columns=['area_acres', 'area_km2'])
np_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   park_name                56 non-null     object
 1   date_established         56 non-null     datetime64[ns]
 2   description              56 non-null     object
 3   state                    56 non-null     object
 4   recreational_visits      56 non-null     float64
 5   non_recreational_visits  56 non-null     float64
 6   recreational_hours       56 non-null     float64
 7   non_recreational_hours   56 non-null     float64
 8   tent_overnights          56 non-null     float64
 9   rv_overnights            56 non-null     float64
 10  backcountry_overnights   56 non-null     float64
 11  num_species              56 non-null     int64
 12  area_sq_miles            56 non-null     float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(3)
memory usage: 5.8+ KB

In [20]:
np_stats

,park_name,date_established,description,state,recreational_visits,non_recreational_visits,recreational_hours,non_recreational_hours,tent_overnights,rv_overnights,backcountry_overnights,num_species,area_sq_miles
0,Acadia,1919-02-26,Covering most of Mount Desert Island and other...,Maine,3879890.0,47100.0,25804425.0,47100.0,120615.0,49074.0,1570.0,1169,76.67
1,Arches,1971-11-12,"This site features more than 2,000 natural san...",Utah,1482045.0,0.0,5462987.0,0.0,14885.0,19602.0,175.0,754,119.81
2,Badlands,1978-11-10,"The Badlands are a collection of buttes, pinna...",South Dakota,1046400.0,55984.0,4418935.0,27992.0,3262.0,910.0,1417.0,756,379.31
3,Big Bend,1944-06-12,Named for the prominent bend in the Rio Grande...,Texas,509129.0,2700.0,9585981.0,8100.0,23647.0,27175.0,58919.0,1991,1251.82
4,Biscayne,1980-06-28,"The central part of Biscayne Bay, this mostly ...",Florida,571242.0,0.0,1809966.0,0.0,1997.0,0.0,0.0,1329,270.27
5,Black Canyon of the Gunnison,1999-10-21,The park protects a quarter of the Gunnison Ri...,Colorado,357069.0,0.0,1918066.0,0.0,17248.0,14690.0,828.0,691,48.09
6,Bryce Canyon,1928-02-25,Bryce Canyon is a geological amphitheater on s...,Utah,2461269.0,408397.0,13210794.0,122520.0,44897.0,44563.0,2667.0,790,55.99
7,Canyonlands,1964-09-12,This landscape was eroded into a maze of canyo...,Utah,800322.0,0.0,5096820.0,0.0,8136.0,8790.0,68953.0,869,527.50
8,Capitol Reef,1971-12-18,The park's Waterpocket Fold is a 100-mile (160...,Utah,1268861.0,87886.0,1928949.0,87886.0,16534.0,31608.0,3115.0,1166,377.98
9,Carlsbad Caverns,1930-05-14,"Carlsbad Caverns has 117 caves, the longest of...",New Mexico,394121.0,0.0,1499159.0,0.0,0.0,0.0,0.0,1429,73.07
10,Channel Islands,1980-03-05,Five of the eight Channel Islands are protecte...,California,328746.0,12197.0,4254417.0,292735.0,0.0,0.0,23881.0,1847,389.94
11,Congaree,2003-11-10,"On the Congaree River, this park is the larges...",South Carolina,250114.0,0.0,999482.0,0.0,7912.0,0.0,614.0,1205,41.71
12,Crater Lake,1902-05-22,Crater Lake lies in the caldera of an ancient ...,Oregon,559976.0,49600.0,3387684.0,24800.0,0.0,0.0,1530.0,1178,286.29
13,Cuyahoga Valley,2000-10-11,This park along the Cuyahoga River has waterfa...,Ohio,2860059.0,0.0,8517581.0,0.0,0.0,0.0,0.0,1589,50.89
14,Death Valley,1994-10-31,"Death Valley is the hottest, lowest, and dries...",California,1099632.0,44158.0,8182261.0,66236.0,71963.0,79442.0,6302.0,1439,5325.62
15,Denali,1917-02-26,"Centered on Denali, the tallest and most promi...",Alaska,498722.0,847073.0,5985104.0,211768.0,0.0,0.0,29720.0,1790,7407.67
16,Dry Tortugas,1992-10-26,"The islands of the Dry Tortugas, at the wester...",Florida,84285.0,1608.0,628830.0,19296.0,6320.0,0.0,0.0,757,101.10
17,Everglades,1934-05-30,The Everglades are the largest tropical wilder...,Florida,810189.0,6000.0,4971781.0,27000.0,0.0,0.0,10411.0,1747,2357.72
18,Gates of the Arctic,1980-12-02,The country's northernmost park protects an ex...,Alaska,11045.0,0.0,101256.0,0.0,0.0,0.0,4000.0,723,11756.09
19,Glacier,1910-05-11,The U.S. half of Waterton-Glacier Internationa...,Montana,2933616.0,2644.0,32739858.0,22876.0,132219.0,132336.0,32074.0,1507,1583.01
20,Glacier Bay,1980-12-02,"Glacier Bay contains tidewater glaciers, mount...",Alaska,703659.0,458.0,8869184.0,96100.0,669.0,0.0,3648.0,917,5036.54
21,Grand Canyon,1919-02-26,"The Grand Canyon, carved by the mighty Colorad...",Arizona,4733705.0,12533.0,74052927.0,12533.0,159019.0,84332.0,299725.0,2626,1877.57
22,Grand Teton,1929-02-26,Grand Teton is the tallest mountain in the sce...,Wyoming,3417106.0,1570845.0,21814250.0,1570845.0,68.0,0.0,41705.0,1855,484.44
23,Great Basin,1986-10-27,"Based around Nevada's second tallest mountain,...",Nevada,143265.0,1200.0,1515358.0,600.0,25844.0,20262.0,453.0,966,120.59
24,Great Sand Dunes,2004-09-24,"The tallest sand dunes in North America, up to...",Colorado,512219.0,470.0,2967583.0,470.0,33106.0,21992.0,10579.0,746,167.73
25,Great Smoky Mountains,1934-06-15,"The Great Smoky Mountains, part of the Appalac...",North Carolina,13297647.0,10832000.0,98083629.0,5416000.0,207070.0,158211.0,84532.0,21287,816.29
26,Guadalupe Mountains,1972-09-30,"This park contains Guadalupe Peak, the highest...",Texas,227340.0,1440.0,645221.0,1440.0,16731.0,8839.0,2508.0,1380,134.95
27,Hot Springs,1921-03-04,Hot Springs was originally established by Cong...,Arkansas,2502967.0,150504.0,6849394.0,171574.0,28.0,22062.0,0.0,594,8.68
28,Indiana Dunes,2019-02-15,"Previously designated a national lakeshore, pa...",Indiana,2765892.0,3943.0,7657687.0,1968.0,24360.0,12540.0,0.0,1888,23.98
29,Isle Royale,1940-04-03,The largest island in Lake Superior is a place...,Michigan,28965.0,94.0,1524902.0,48484.0,6166.0,0.0,30072.0,1225,893.42
30,Joshua Tree,1994-10-31,Covering large areas of the Colorado and Mojav...,California,3270404.0,12171.0,19156045.0,12171.0,200056.0,101514.0,17396.0,846,1242.43
31,Katmai,1980-12-02,This park on the Alaska Peninsula protects the...,Alaska,33763.0,7025.0,609721.0,101346.0,6172.0,0.0,5564.0,1326,5741.45
32,Kenai Fjords,1980-12-02,"Near Seward on the Kenai Peninsula, this park ...",Alaska,387525.0,0.0,1237607.0,0.0,688.0,0.0,57.0,1218,1046.33
33,Kobuk Valley,1980-12-02,Kobuk Valley protects 61 miles (98 km) of the ...,Alaska,17616.0,7700.0,226149.0,233200.0,0.0,0.0,6675.0,554,2735.49
34,Lake Clark,1980-12-02,The region around Lake Clark features four act...,Alaska,16728.0,3223.0,142378.0,37862.0,0.0,0.0,4555.0,1732,4093.46
35,Lassen Volcanic,1916-08-09,"Lassen Peak, the largest lava dome volcano in ...",California,418978.0,0.0,4111590.0,0.0,43752.0,21273.0,1168.0,1054,166.55
36,Mammoth Cave,1941-07-01,With more than 400 miles (640 km) of passagewa...,Kentucky,654450.0,110436.0,5182291.0,55217.0,49753.0,20081.0,4378.0,1980,113.24
37,Mesa Verde,1906-06-29,"This area constitutes over 4,000 archaeologica...",Colorado,505194.0,11860.0,3524612.0,11860.0,22008.0,28868.0,0.0,1102,82.01
38,Mount Rainier,1899-03-02,"Mount Rainier, an active stratovolcano, is the...",Washington,1674294.0,849082.0,21060484.0,849082.0,59749.0,29628.0,53949.0,1195,369.35
39,New River Gorge,2020-12-27,The New River Gorge is the deepest river gorge...,West Virginia,1707223.0,2400.0,4447173.0,4800.0,17214.0,10501.0,12609.0,2766,10.97
40,North Cascades,1968-10-02,The highly glaciated mountains of the North Ca...,Washington,40351.0,0.0,531844.0,0.0,0.0,0.0,19125.0,2969,788.72
41,Olympic,1938-06-29,This park on the Olympic Peninsula includes a ...,Washington,2947503.0,1045102.0,15497301.0,336937.0,121314.0,91536.0,158254.0,1376,1441.64
42,Petrified Forest,1962-12-09,This portion of the Chinle Formation has a lar...,Arizona,520491.0,120.0,1350691.0,120.0,0.0,0.0,722.0,727,345.92
43,Pinnacles,2013-01-10,Named for the eroded leftovers of a portion of...,California,341220.0,0.0,1925335.0,0.0,0.0,0.0,0.0,1180,41.70
44,Redwood,1968-10-02,This park and the co-managed state parks prote...,California,409105.0,10824.0,1773959.0,2724.0,6554.0,0.0,13094.0,1461,217.19
45,Rocky Mountain,1915-01-26,Bisected north to south by the Continental Div...,Colorado,4115837.0,8750.0,26835519.0,26250.0,70761.0,28329.0,34314.0,1365,415.39
46,Saguaro,1994-10-14,Split into the separate Rincon Mountain and Tu...,Arizona,1010906.0,4395013.0,1887764.0,1098754.0,0.0,0.0,3515.0,1572,145.12
47,Shenandoah,1935-12-26,Shenandoah's Blue Ridge Mountains are covered ...,Virginia,1576008.0,10962.0,10914844.0,2742.0,122031.0,67815.0,67738.0,2569,313.20
48,Theodore Roosevelt,1978-11-10,This region that enticed and influenced Presid...,North Dakota,746862.0,6578.0,2662270.0,2172.0,11703.0,21459.0,718.0,785,110.07
49,Virgin Islands,1956-08-02,This island park on Saint John preserves prist...,U.S. Virgin Islands,343685.0,231252.0,2113667.0,70278.0,0.0,0.0,0.0,965,23.52
50,Voyageurs,1975-04-08,This park protecting four lakes near the Canad...,Minnesota,220825.0,0.0,944753.0,0.0,0.0,0.0,56364.0,1144,340.97
51,White Sands,2019-12-20,"Located in the mountain-ringed Tularosa Basin,...",New Mexico,729096.0,0.0,1425910.0,0.0,0.0,0.0,0.0,525,228.66
52,Wind Cave,1903-01-09,Wind Cave is distinctive for its calcite fin f...,South Dakota,592459.0,236892.0,1826057.0,78174.0,5396.0,6500.0,544.0,991,53.08
53,Yellowstone,1872-03-01,"Situated on the Yellowstone Caldera, the park ...",Wyoming,4501382.0,1306861.0,81677408.0,752457.0,25295.0,30413.0,38262.0,2076,3468.42
54,Yosemite,1890-10-01,"Yosemite features sheer granite cliffs, except...",California,3897070.0,160167.0,52057099.0,4245429.0,275278.0,196092.0,103997.0,1904,1190.23
55,Zion,1919-11-19,Located at the junction of the Colorado Platea...,Utah,4623238.0,21900.0,29471316.0,5475.0,100411.0,85948.0,8497.0,1319,230.07

In [21]:
np_stats['species_per_sq_mile'] = np_stats.apply(lambda x: round(x.num_species / x.area_sq_miles, 2), axis=1)

In [22]:
np_stats['rec_hours_per_sq_mile'] = np_stats.apply(lambda x: round(x.recreational_hours / x.area_sq_miles, 2), axis=1)

In [23]:
np_stats['non_rec_hours_per_sq_mile'] = np_stats.apply(lambda x: round(x.non_recreational_hours / x.area_sq_miles, 2), axis=1)

In [24]:
np_stats['rec_hours_per_visit'] = np_stats.apply(lambda x: round(x.recreational_hours / x.recreational_visits, 2), axis=1)

In [25]:
def nonRecHrPerVisit(hours, visits):
    try:
        result = round(hours / visits, 2)
        return result
    except:
        return 0.0

In [26]:
np_stats['non_rec_hours_per_visit'] = np_stats.apply(lambda x: nonRecHrPerVisit(x.non_recreational_hours, x.non_recreational_visits), axis=1)

In [27]:
np_stats

,park_name,date_established,description,state,recreational_visits,non_recreational_visits,recreational_hours,non_recreational_hours,tent_overnights,rv_overnights,backcountry_overnights,num_species,area_sq_miles,species_per_sq_mile,rec_hours_per_sq_mile,non_rec_hours_per_sq_mile,rec_hours_per_visit,non_rec_hours_per_visit
0,Acadia,1919-02-26,Covering most of Mount Desert Island and other...,Maine,3879890.0,47100.0,25804425.0,47100.0,120615.0,49074.0,1570.0,1169,76.67,15.25,336564.82,614.32,6.65,1.00
1,Arches,1971-11-12,"This site features more than 2,000 natural san...",Utah,1482045.0,0.0,5462987.0,0.0,14885.0,19602.0,175.0,754,119.81,6.29,45597.09,0.00,3.69,0.00
2,Badlands,1978-11-10,"The Badlands are a collection of buttes, pinna...",South Dakota,1046400.0,55984.0,4418935.0,27992.0,3262.0,910.0,1417.0,756,379.31,1.99,11649.93,73.80,4.22,0.50
3,Big Bend,1944-06-12,Named for the prominent bend in the Rio Grande...,Texas,509129.0,2700.0,9585981.0,8100.0,23647.0,27175.0,58919.0,1991,1251.82,1.59,7657.64,6.47,18.83,3.00
4,Biscayne,1980-06-28,"The central part of Biscayne Bay, this mostly ...",Florida,571242.0,0.0,1809966.0,0.0,1997.0,0.0,0.0,1329,270.27,4.92,6696.88,0.00,3.17,0.00
5,Black Canyon of the Gunnison,1999-10-21,The park protects a quarter of the Gunnison Ri...,Colorado,357069.0,0.0,1918066.0,0.0,17248.0,14690.0,828.0,691,48.09,14.37,39884.92,0.00,5.37,0.00
6,Bryce Canyon,1928-02-25,Bryce Canyon is a geological amphitheater on s...,Utah,2461269.0,408397.0,13210794.0,122520.0,44897.0,44563.0,2667.0,790,55.99,14.11,235949.17,2188.25,5.37,0.30
7,Canyonlands,1964-09-12,This landscape was eroded into a maze of canyo...,Utah,800322.0,0.0,5096820.0,0.0,8136.0,8790.0,68953.0,869,527.50,1.65,9662.22,0.00,6.37,0.00
8,Capitol Reef,1971-12-18,The park's Waterpocket Fold is a 100-mile (160...,Utah,1268861.0,87886.0,1928949.0,87886.0,16534.0,31608.0,3115.0,1166,377.98,3.08,5103.31,232.51,1.52,1.00
9,Carlsbad Caverns,1930-05-14,"Carlsbad Caverns has 117 caves, the longest of...",New Mexico,394121.0,0.0,1499159.0,0.0,0.0,0.0,0.0,1429,73.07,19.56,20516.75,0.00,3.80,0.00
10,Channel Islands,1980-03-05,Five of the eight Channel Islands are protecte...,California,328746.0,12197.0,4254417.0,292735.0,0.0,0.0,23881.0,1847,389.94,4.74,10910.44,750.72,12.94,24.00
11,Congaree,2003-11-10,"On the Congaree River, this park is the larges...",South Carolina,250114.0,0.0,999482.0,0.0,7912.0,0.0,614.0,1205,41.71,28.89,23962.65,0.00,4.00,0.00
12,Crater Lake,1902-05-22,Crater Lake lies in the caldera of an ancient ...,Oregon,559976.0,49600.0,3387684.0,24800.0,0.0,0.0,1530.0,1178,286.29,4.11,11833.05,86.63,6.05,0.50
13,Cuyahoga Valley,2000-10-11,This park along the Cuyahoga River has waterfa...,Ohio,2860059.0,0.0,8517581.0,0.0,0.0,0.0,0.0,1589,50.89,31.22,167372.39,0.00,2.98,0.00
14,Death Valley,1994-10-31,"Death Valley is the hottest, lowest, and dries...",California,1099632.0,44158.0,8182261.0,66236.0,71963.0,79442.0,6302.0,1439,5325.62,0.27,1536.40,12.44,7.44,1.50
15,Denali,1917-02-26,"Centered on Denali, the tallest and most promi...",Alaska,498722.0,847073.0,5985104.0,211768.0,0.0,0.0,29720.0,1790,7407.67,0.24,807.96,28.59,12.00,0.25
16,Dry Tortugas,1992-10-26,"The islands of the Dry Tortugas, at the wester...",Florida,84285.0,1608.0,628830.0,19296.0,6320.0,0.0,0.0,757,101.10,7.49,6219.88,190.86,7.46,12.00
17,Everglades,1934-05-30,The Everglades are the largest tropical wilder...,Florida,810189.0,6000.0,4971781.0,27000.0,0.0,0.0,10411.0,1747,2357.72,0.74,2108.72,11.45,6.14,4.50
18,Gates of the Arctic,1980-12-02,The country's northernmost park protects an ex...,Alaska,11045.0,0.0,101256.0,0.0,0.0,0.0,4000.0,723,11756.09,0.06,8.61,0.00,9.17,0.00
19,Glacier,1910-05-11,The U.S. half of Waterton-Glacier Internationa...,Montana,2933616.0,2644.0,32739858.0,22876.0,132219.0,132336.0,32074.0,1507,1583.01,0.95,20682.03,14.45,11.16,8.65
20,Glacier Bay,1980-12-02,"Glacier Bay contains tidewater glaciers, mount...",Alaska,703659.0,458.0,8869184.0,96100.0,669.0,0.0,3648.0,917,5036.54,0.18,1760.97,19.08,12.60,209.83
21,Grand Canyon,1919-02-26,"The Grand Canyon, carved by the mighty Colorad...",Arizona,4733705.0,12533.0,74052927.0,12533.0,159019.0,84332.0,299725.0,2626,1877.57,1.40,39440.83,6.68,15.64,1.00
22,Grand Teton,1929-02-26,Grand Teton is the tallest mountain in the sce...,Wyoming,3417106.0,1570845.0,21814250.0,1570845.0,68.0,0.0,41705.0,1855,484.44,3.83,45029.83,3242.60,6.38,1.00
23,Great Basin,1986-10-27,"Based around Nevada's second tallest mountain,...",Nevada,143265.0,1200.0,1515358.0,600.0,25844.0,20262.0,453.0,966,120.59,8.01,12566.20,4.98,10.58,0.50
24,Great Sand Dunes,2004-09-24,"The tallest sand dunes in North America, up to...",Colorado,512219.0,470.0,2967583.0,470.0,33106.0,21992.0,10579.0,746,167.73,4.45,17692.62,2.80,5.79,1.00
25,Great Smoky Mountains,1934-06-15,"The Great Smoky Mountains, part of the Appalac...",North Carolina,13297647.0,10832000.0,98083629.0,5416000.0,207070.0,158211.0,84532.0,21287,816.29,26.08,120157.82,6634.90,7.38,0.50
26,Guadalupe Mountains,1972-09-30,"This park contains Guadalupe Peak, the highest...",Texas,227340.0,1440.0,645221.0,1440.0,16731.0,8839.0,2508.0,1380,134.95,10.23,4781.19,10.67,2.84,1.00
27,Hot Springs,1921-03-04,Hot Springs was originally established by Cong...,Arkansas,2502967.0,150504.0,6849394.0,171574.0,28.0,22062.0,0.0,594,8.68,68.43,789100.69,19766.59,2.74,1.14
28,Indiana Dunes,2019-02-15,"Previously designated a national lakeshore, pa...",Indiana,2765892.0,3943.0,7657687.0,1968.0,24360.0,12540.0,0.0,1888,23.98,78.73,319336.41,82.07,2.77,0.50
29,Isle Royale,1940-04-03,The largest island in Lake Superior is a place...,Michigan,28965.0,94.0,1524902.0,48484.0,6166.0,0.0,30072.0,1225,893.42,1.37,1706.81,54.27,52.65,515.79
30,Joshua Tree,1994-10-31,Covering large areas of the Colorado and Mojav...,California,3270404.0,12171.0,19156045.0,12171.0,200056.0,101514.0,17396.0,846,1242.43,0.68,15418.21,9.80,5.86,1.00
31,Katmai,1980-12-02,This park on the Alaska Peninsula protects the...,Alaska,33763.0,7025.0,609721.0,101346.0,6172.0,0.0,5564.0,1326,5741.45,0.23,106.20,17.65,18.06,14.43
32,Kenai Fjords,1980-12-02,"Near Seward on the Kenai Peninsula, this park ...",Alaska,387525.0,0.0,1237607.0,0.0,688.0,0.0,57.0,1218,1046.33,1.16,1182.81,0.00,3.19,0.00
33,Kobuk Valley,1980-12-02,Kobuk Valley protects 61 miles (98 km) of the ...,Alaska,17616.0,7700.0,226149.0,233200.0,0.0,0.0,6675.0,554,2735.49,0.20,82.67,85.25,12.84,30.29
34,Lake Clark,1980-12-02,The region around Lake Clark features four act...,Alaska,16728.0,3223.0,142378.0,37862.0,0.0,0.0,4555.0,1732,4093.46,0.42,34.78,9.25,8.51,11.75
35,Lassen Volcanic,1916-08-09,"Lassen Peak, the largest lava dome volcano in ...",California,418978.0,0.0,4111590.0,0.0,43752.0,21273.0,1168.0,1054,166.55,6.33,24686.82,0.00,9.81,0.00
36,Mammoth Cave,1941-07-01,With more than 400 miles (640 km) of passagewa...,Kentucky,654450.0,110436.0,5182291.0,55217.0,49753.0,20081.0,4378.0,1980,113.24,17.48,45763.78,487.61,7.92,0.50
37,Mesa Verde,1906-06-29,"This area constitutes over 4,000 archaeologica...",Colorado,505194.0,11860.0,3524612.0,11860.0,22008.0,28868.0,0.0,1102,82.01,13.44,42977.83,144.62,6.98,1.00
38,Mount Rainier,1899-03-02,"Mount Rainier, an active stratovolcano, is the...",Washington,1674294.0,849082.0,21060484.0,849082.0,59749.0,29628.0,53949.0,1195,369.35,3.24,57020.40,2298.85,12.58,1.00
39,New River Gorge,2020-12-27,The New River Gorge is the deepest river gorge...,West Virginia,1707223.0,2400.0,4447173.0,4800.0,17214.0,10501.0,12609.0,2766,10.97,252.14,405394.07,437.56,2.60,2.00
40,North Cascades,1968-10-02,The highly glaciated mountains of the North Ca...,Washington,40351.0,0.0,531844.0,0.0,0.0,0.0,19125.0,2969,788.72,3.76,674.31,0.00,13.18,0.00
41,Olympic,1938-06-29,This park on the Olympic Peninsula includes a ...,Washington,2947503.0,1045102.0,15497301.0,336937.0,121314.0,91536.0,158254.0,1376,1441.64,0.95,10749.77,233.72,5.26,0.32
42,Petrified Forest,1962-12-09,This portion of the Chinle Formation has a lar...,Arizona,520491.0,120.0,1350691.0,120.0,0.0,0.0,722.0,727,345.92,2.10,3904.63,0.35,2.60,1.00
43,Pinnacles,2013-01-10,Named for the eroded leftovers of a portion of...,California,341220.0,0.0,1925335.0,0.0,0.0,0.0,0.0,1180,41.70,28.30,46171.10,0.00,5.64,0.00
44,Redwood,1968-10-02,This park and the co-managed state parks prote...,California,409105.0,10824.0,1773959.0,2724.0,6554.0,0.0,13094.0,1461,217.19,6.73,8167.77,12.54,4.34,0.25
45,Rocky Mountain,1915-01-26,Bisected north to south by the Continental Div...,Colorado,4115837.0,8750.0,26835519.0,26250.0,70761.0,28329.0,34314.0,1365,415.39,3.29,64603.19,63.19,6.52,3.00
46,Saguaro,1994-10-14,Split into the separate Rincon Mountain and Tu...,Arizona,1010906.0,4395013.0,1887764.0,1098754.0,0.0,0.0,3515.0,1572,145.12,10.83,13008.30,7571.35,1.87,0.25
47,Shenandoah,1935-12-26,Shenandoah's Blue Ridge Mountains are covered ...,Virginia,1576008.0,10962.0,10914844.0,2742.0,122031.0,67815.0,67738.0,2569,313.20,8.20,34849.44,8.75,6.93,0.25
48,Theodore Roosevelt,1978-11-10,This region that enticed and influenced Presid...,North Dakota,746862.0,6578.0,2662270.0,2172.0,11703.0,21459.0,718.0,785,110.07,7.13,24187.06,19.73,3.56,0.33
49,Virgin Islands,1956-08-02,This island park on Saint John preserves prist...,U.S. Virgin Islands,343685.0,231252.0,2113667.0,70278.0,0.0,0.0,0.0,965,23.52,41.03,89866.79,2988.01,6.15,0.30
50,Voyageurs,1975-04-08,This park protecting four lakes near the Canad...,Minnesota,220825.0,0.0,944753.0,0.0,0.0,0.0,56364.0,1144,340.97,3.36,2770.78,0.00,4.28,0.00
51,White Sands,2019-12-20,"Located in the mountain-ringed Tularosa Basin,...",New Mexico,729096.0,0.0,1425910.0,0.0,0.0,0.0,0.0,525,228.66,2.30,6235.94,0.00,1.96,0.00
52,Wind Cave,1903-01-09,Wind Cave is distinctive for its calcite fin f...,South Dakota,592459.0,236892.0,1826057.0,78174.0,5396.0,6500.0,544.0,991,53.08,18.67,34401.98,1472.76,3.08,0.33
53,Yellowstone,1872-03-01,"Situated on the Yellowstone Caldera, the park ...",Wyoming,4501382.0,1306861.0,81677408.0,752457.0,25295.0,30413.0,38262.0,2076,3468.42,0.60,23548.88,216.95,18.14,0.58
54,Yosemite,1890-10-01,"Yosemite features sheer granite cliffs, except...",California,3897070.0,160167.0,52057099.0,4245429.0,275278.0,196092.0,103997.0,1904,1190.23,1.60,43737.01,3566.90,13.36,26.51
55,Zion,1919-11-19,Located at the junction of the Colorado Platea...,Utah,4623238.0,21900.0,29471316.0,5475.0,100411.0,85948.0,8497.0,1319,230.07,5.73,128097.17,23.80,6.37,0.25

In [29]:
np_stats.to_csv('../data/np_all.csv', index=False)